=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED1_formalismeXML/Codes/OLDIES/labo.dtd
<!ELEMENT laboratoire (directeur,equipe+,projet*)>
 <!ELEMENT directeur (#PCDATA)>
 <!ELEMENT equipe (directeur)>
 <!ATTLIST equipe
	 id ID #REQUIRED
	 nom CDATA #REQUIRED
	 ref_projet IDREFS #REQUIRED
	 >
 <!ELEMENT projet (directeur)>
 <!ATTLIST projet
	 nom ID #REQUIRED
	 ref_equipes IDREFS #REQUIRED
	 >

=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED1_formalismeXML/Codes/OLDIES/labo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 <!DOCTYPE laboratoire SYSTEM "labo.dtd">
 <laboratoire>
 <directeur>Michel Beaudouin-Lafon</directeur>
 <equipe id="prog" nom="Programmation" ref_projets="InSitu">
	 <directeur>Marie-Claude Gaudel</directeur>
 </equipe>
 <equipe id="demon" nom="Demonstration" ref_projets="Logical">
	 <directeur>Christine Paulin</directeur>
 </equipe>
 <equipe id="iasi" nom="Intelligence Artificielle et Systemes d'Inference" ref_projets="GEMO">
	 <directeur>Marie-Christine Rousset</directeur>
 </equipe>
 <equipe id="ia" nom="Inference et Apprentissage" ref_projets="TAO">
	 <directeur>Michele Sebag</directeur>
 </equipe>
 <projet nom="GEMO" ref_equipes="iasi">
	 <directeur>Serge Abiteboul</directeur>
 </projet>
 <projet nom="TAO"  ref_equipes="ia">
	 <directeur>Marc Shoenauer</directeur>
 </projet>
 <projet nom="InSitu"  ref_equipes="prog">
	 <directeur>Wendy Mackay</directeur>
 </projet>
 <projet nom="Logical" ref_equipes="demon" "prog">
	 <directeur>Gilles Dowek</directeur>
 </projet>
 </laboratoire>
