=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED4_XMLSchema/Codes/dvd.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="DVDType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="cb" type="xs:string" use="required" />
    <xs:attribute name="iddis" type="xs:string" use="required" />
  </xs:complexType>
  
  <xs:simpleType name="genreType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="Drame"/>
      <xs:enumeration value="Comedie"/>
      <xs:enumeration value="Action"/>
      <xs:enumeration value="Jeunesse"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="dispoType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="Y"/>
      <xs:enumeration value="N"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="DVDdescrType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="cb" type="xs:string"/>
        <xs:attribute name="real" type="xs:string"/>
        <xs:attribute name="genre" type="genreType"/>
        <xs:attribute name="disponibilite" type="dispoType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="DistribType">
    <xs:sequence>
      <xs:element name="Adresse">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="Num" type="xs:string"/>
	    <xs:element name="Rue" type="xs:string"/>
	    <xs:element name="Ville" type="xs:string"/>
	    <xs:element name="CP" type="xs:integer"/>
	  </xs:sequence>
	</xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
  
  <xs:element name="BD">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="DVD" type="DVDType" minOccurs="1" maxOccurs="unbounded"/>
	<xs:element name="DVDdescr" type="DVDdescrType" minOccurs="1" maxOccurs="unbounded"/>
	<xs:element name="Distrib" type="DistribType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED4_XMLSchema/Codes/dvd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<BD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="dvd.xsd">
<DVD id="dvd0" cb="_5414474401006" iddis="dis0"/>
<DVD id="dvd1" cb="_5414474401006" iddis="dis1"/>
<DVD id="dvd2" cb="_3259119658825" iddis="dis0"/>
<DVD id="dvd3" cb="_5414474401006" iddis="dis1"/>
<DVD id="dvd4" cb="_1234567891234" iddis="dis0"/>
<DVD id="dvd5" cb="_5414474401006" iddis="dis0"/>
<DVD id="dvd6" cb="_1234567891234" iddis="dis1"/>
<DVD id="dvd7" cb="_5414474401006" iddis="dis0"/>
<DVD id="dvd8" cb="_5414474401006" iddis="dis1"/>
<DVD id="dvd9" cb="_3259119658825" iddis="dis0"/>

<DVDdescr cb="_5414474401006" real="Tarantino" genre="Action" disponibilite="Y">Kill Bill</DVDdescr>
<DVDdescr cb="_3259119658825" real="Lynch" genre="Drame" disponibilite="Y">Mulholland Drive</DVDdescr>
<DVDdescr cb="_1234567891234" real="Dellanoy" genre="Comedie"  disponibilite="N">Le lit a deux place</DVDdescr>

<Distrib id="dis0">
  <Adresse>
    <Num>3</Num>
    <Rue>Rue de Paris</Rue>
    <Ville>Orsay</Ville>
    <CP>91400</CP>
  </Adresse>
</Distrib>

<Distrib id="dis1">
  <Adresse>
    <Num>38</Num>
    <Rue>Boulevard Dubreuil</Rue>
    <Ville>Orsay</Ville>
    <CP>91400</CP>
  </Adresse>
</Distrib>

</BD>
