=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED4_XMLSchema/Codes/produits.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="identType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]-[0-9]{4}(-[A-E])?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="quantityType">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="deviseType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="USD"/>
      <xs:enumeration value="EUR"/>
      <xs:enumeration value="GBP"/>
      <xs:enumeration value="JPY"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
	<xs:attribute name="Devises" type="deviseType" use="optional" default="EUR"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="produitType">
    <xs:sequence>
      <xs:element name="lib" type="xs:string" minOccurs="1" />
      <xs:element name="Quantity" type="quantityType" minOccurs="1" />
      <xs:element name="Price" type="priceType" minOccurs="1" maxOccurs="4"/>
      <xs:element name="Date" type="xs:date" minOccurs="0" maxOccurs="1"/>		
    </xs:sequence>
    <xs:attribute name="ID" type="identType" use="required" />
  </xs:complexType>
  
  <xs:element name="Produits">
    <xs:complexType>
      <xs:sequence>
      <xs:element name="Produit" type="produitType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== rigaux/b3d/supports/Partie1-XML/sources_ED/ED4_XMLSchema/Codes/produits.xml
<?xml version="1.0" encoding="UTF-8"?>
<Produits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="produits.xsd">
  <Produit ID="3-5670-C">
    <lib>Dady Mam - biberon</lib>
    <Quantity>91</Quantity>
    <Price Devises="EUR">7.90</Price>
    <Date>2008-12-03</Date>
  </Produit>
  <Produit ID="7-9997-B">
    <lib>Mc Traveler - Poussette</lib>
    <Quantity>57</Quantity>
    <Price Devises="JPY">22000</Price>
    <Date>2007-12-22</Date>
  </Produit>
  <Produit ID="2-3478-A">
    <lib>BB trop confort - Table a langer</lib>
    <Quantity>27</Quantity>
    <Price Devises="USD">75</Price>
    <Date>2009-06-01</Date>
  </Produit>
  <Produit ID="5-6767-A">
    <lib>BB Naturel - Set bain</lib>
    <Quantity>28</Quantity>
    <Price Devises="GBP">12</Price>
    <Date>2010-01-02</Date>
  </Produit>
  <Produit ID="5-6867-A">
    <lib>BB Naturel - set 3 bodies</lib>
    <Quantity>23</Quantity>
    <Price Devises="EUR">12</Price>
    <Date>2010-01-02</Date>
  </Produit>
</Produits>
